spring:
  datasource:
    url: jdbc:h2:~/test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  main:
    allow-bean-definition-overriding: true
